services:
  postgres:
    image: postgres:17-alpine
    # container_name: system_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: erp_v1
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    # container_name: system_cache
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    # container_name: system_mq
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - mqdata:/var/lib/rabbitmq

  minio:
    image: minio/minio:latest
    # container_name: system_storage
    restart: always
    ports:
      - "9001:9000" # API Port (S3 Compatible)
      - "9002:9001" # Web UI Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: securepassword
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc:latest
    # container_name: system_storage_setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 admin securepassword;
      /usr/bin/mc mb myminio/crm-files --ignore-existing;
      /usr/bin/mc anonymous set none myminio/crm-files;
      exit 0;
      "

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    # container_name: system_api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - minio

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    # container_name: system_worker
    restart: always
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - minio

volumes:
  pgdata:
  redisdata:
  mqdata:
  miniodata: # NEW
